name: CTFPlugin
version: ${project.version}
main: ctf.ctfplugin.CTFPlugin
api-version: 1.19
commands:
  join:
    description: Joins a team.
    usage: /<command> [red|blue|spectator]
    permission: ranks.player
  maps:
    description: Lists all maps.
    usage: /<command>
    permission: ranks.player
  visit:
    description: Visits a map.
    usage: /<command> [map name]
    permission: ranks.player
